repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: '^integration/benchmarks/'
      - id: ruff-formatter
        exclude: '^integration/benchmarks/'

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.313
    hooks:
      - id: pyright
        args: [integration, reflex, tests]
        language: system

  - repo: local
    hooks:
      - id: update-pyi-files
        name: update-pyi-files
        always_run: true
        language: system
        description: 'Update pyi files as needed'
        entry: python scripts/pyi_generator.py
